### ISSUE TITLE
Front end for authentication via Twitter

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#11]
When a crowd participant opens the Truman app, they will see a landing page to create an account in Truman / sign into Truman.

If they reached the page with a link that includes the worker ID, the form will be pre-populated with that ID. If not, they can enter it into the form.

They then need to click a "sign in" button  (or "sign up" if this is the first time), this will start the Twitter authentication workflow ([see Twitter Developer Doc](https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter)). 

~~When the user clicks on the button, on the database we will create a mapping between the worker ID (from MTurk / Prime Panels) and the Twitter handle of the authenticating user. ~~

After authentication is successful, the OAuth will redirect to a landing page. If the Twitter account in which they signed is the same on file, them we will start loading the data. There will be a spinning wheel graphics, showing that the data are being loaded, and to wait for a few seconds.

If the account is not the same, we will tell them they need to log out and log into Twitter again, with the correct account.

**Comment by glciampaglia** [comment]
We decided that we will implement this in postgresql, so we will also need to change from the current code, which uses Mongo. See #3.

**Comment by glciampaglia** [comment]
We discussed the issue again, we realized that if a crowd worker has multiple Twitter accounts, we need to make sure that they sign into Twitter with the same account provided when doing the eligibility survey.

**Comment by glciampaglia** [comment]
We are currently very close to get this working. There is error related to CORS policy, we will investigate.

**Comment by saumyabhadani95** [comment]
Done.
