### ISSUE TITLE
Deploy docker image on AWS

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#12]
As a follow up to issue #5, now that we have a working docker image, we would like to deploy it on AWS so that we can start playing with Truman on a remote server. We decided that we will use an AWS image instead of a docker image, and that the database will use RDS, so that we can take full advantage of Amazon EC2's resizing capabilities, in case we need to spawn multiple instances of the app. All the instances will use the same database. 

We need to complete the following:
* [x] Decide on the fields of the database (#3)
* [x] Set up database on Amazon RDS (#13)
* [x] Create EC2 instance for testing
* [x] Make a template out of it (see comment below)
* ~~Change the script that creates a docker image from the Github repo to create an AWS image instead~~

**Comment by RobertAndion** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html#creating-an-ami

**Comment by RobertAndion** [comment]
It seems that you can create a regular EC2 instance and fully install our code on it, then I can create an AMI image based off of the customized EC2 instance and generate more of them from it. I propose this as a way to create our AMI (AWS Image equivalent to a docker image essentially) image.

**Comment by glciampaglia** [comment]
We deployed a quick instance for Brendan, so we got the basics down. We will get a host name (see #22) for the future.

**Comment by RobertAndion** [comment]
This is done and the beta version is deployed. We can now template this AWS instance whenever we choose to.
