### ISSUE TITLE
Create development database on RDS

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#13]
Based on #3, we will create a new database on Amazon RDS and start using it for development only. Later, when it is time to run the experiment, we will create a separate one for production.

**Comment by RobertAndion** [comment]
The beta database is up and running. I have created it on RDS with the proper tables and fields for now. We need to add what we want from tweets in a more specific fashion. We also need to create the code to modify it (Starting on this tomorrow).

**Comment by glciampaglia** [comment]
Closing.
