### ISSUE TITLE
Get List of Friends from screening survey

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#17]
As part of the screening survey, we need to know who are the users that the MTurk worker follows on Twitter. 

This can be done in the authorizer app (see #6), using the [GET friends/ids](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids) method (v1 API) or [GET /2/users/:id/following](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-following) (v2 API). 

Both methods allows to make 15 requests every 15 minutes (user auth, aka OAuth 1.0a User Context). For v1, each request can return up to 5,000 IDs. That's a total of 75,000 "friends". For v2, each requests can return up to 1,000 IDs, for a total for 15,000. So we should probably use the v1 endpoint.

We discussed and we think it's unlikely many people follow more than that, so we think the safest would be to fire up all the 15 requests at once. This would allow us to get the data before the token from the 3-legged oauth (user auth) expires or the user logs out from the authorizer app. 

In case a few users have more than 75,000 friends, then we can collect them at a separate time, using our own app keys (bearer token oauth, see below).

**Comment by saumyabhadani95** [comment]
We can user this endpoint from our **own bearer token** : https://developer.twitter.com/en/docs/twitter-api/users/follows/introduction

**Comment by glciampaglia** [comment]
Description to make clear we use OAuth 1.0a User Context for auth. The "token" is not the bearer token (different OAuth protocol), but the token returned from the 3-legged OAuth flow (also known as app authentication).

**Comment by glciampaglia** [comment]
We have implemented this for v2, but later we realized that there are different limits, and that v1 can return more, so we will switch to v1.

**Comment by saumyabhadani95** [comment]
Switched to v1.
