### ISSUE TITLE
Integrate Twitter authentication for news ranking survey

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#2]
Right now we have to run a script manually. We need to run this script automatically when the user clicks on a button.

**Comment by saumyabhadani95** [comment]
Professor, does this issue also include adding the screening step to the authentication script, which is determining the number of accounts the user follow and determining their last liked tweet?

**Comment by saumyabhadani95** [comment]
Done.
