### ISSUE TITLE
Manage multiple connections to Amazon RDS via shared connection pool

### ISSUE THREAD

**Issue by saumyabhadani95** [glciampaglia/infodiversity-mock-social-media#21]
The database is running on Amazon RDS. To insert into the database tables, we are planning to create a database object for every user in Python. Till now we have decided that once the user logs in through the Twitter authenticator, the python code responsible to building the home timeline (guest_access_twitter_flask.py) will create the database object and insert the new session into the Sessions table. Now the challenge is to use the same object to fill the rest of the tables also (engagement metrics). We cannot use different objects as we cannot keep opening and closing the connection from Amazon RDS as it will make the platform very slow.

**Comment by glciampaglia** [comment]
This sounds like something that can be solved using a connection pool: https://www.psycopg.org/docs/pool.html

**Comment by RobertAndion** [comment]
The basis of the new pool class has been made. It needs extensive testing and it needs to be ran to make sure it can connect to a database. We also must decide where to make this object so it is global scope. (Perhaps a Python server that creates the object at launch and has functions that deals with opening and closing connections on a user/function basis?)

**Comment by glciampaglia** [comment]
How about [this approach](https://webcache.googleusercontent.com/search?q=cache:WG1pHQ-sYgQJ:https://paullockaby.com/archive/2019/09/flask-connection-pool-for-postgresql/+&cd=3&hl=en&ct=clnk&gl=us&client=ubuntu)? (The [original website](https://paullockaby.com/archive/2019/09/flask-connection-pool-for-postgresql/) seems down, link is to Google cached version.). The gist with the code is here: https://gist.github.com/plockaby/6fcdf51148f8b7035b8f451ebe583a82

**Comment by RobertAndion** [comment]
That looks very promising I will adjust mine to be more like that. I have a similar framework. I have now also created a Flask server with the pool object at File scope so it will survive the entire time the app is running, the functions inside will then request and close connections as needed.

**Comment by glciampaglia** [comment]
We have an implementation working, we need make sure we commit at the end of it.

**Comment by glciampaglia** [comment]
This is done.
