### ISSUE TITLE
Run EC2 instance from USF subdomain

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#22]
We can run under `cse.usf.edu/NAME`. @glciampaglia will ask Marbin how to do it.

**Comment by glciampaglia** [comment]
We wrote to Marbin.

**Comment by glciampaglia** [comment]
Marbin and Minh set up for a reverse proxy on https://infodiversity.cse.usf.edu/ 

However, Minh reported that there is an error from AWS internal. Maybe we are expecting additional information that the reverse proxy server is not sending. We should check the error log on AWS.

**Comment by glciampaglia** [comment]
We will create a new twitter app that uses infodiversity as the callback domain. This should fix the problem, since they are already using the correct port number.

**Comment by saumyabhadani95** [comment]
The app should be working from the USF subdomain now through this [link](https://infodiversity.cse.usf.edu/).

However when we enter the feed, the IP appears as "3.19.232.97:3000/?access_token=......". 
I guess we don't want that? Closing this issue for now.

**Comment by RobertAndion** [comment]
If we have them forward the ip to only the ip (without port 5000) we can not have this issue the only problem will be the port number will be visible which would be unsightly unless theres a SRV record we can set up (not sure how to do that on a custom application)

**Comment by glciampaglia** [comment]
I wrote back to Minh and Marbin and asked to update the reverse proxy settings.
