### ISSUE TITLE
Find name for this app

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#23]
Possible candidates:
- tweedu
- smartfeed

Once we have enough candidates we will decide, either via a vote or brainstorming.

**Comment by RobertAndion** [comment]
-Adjustafeed
-Politicy

**Comment by saumyabhadani95** [comment]
EscapeMisInfo (EMI)

**Comment by glciampaglia** [comment]
Robert suggested: rockwell - somebody's watching me.

**Comment by glciampaglia** [comment]
We have decided that we will do something similar to what the Cornell group did --- the software and the experimental website should have different branding names. 

For the software, we can call it Rockwell. 

For the public website of the survey, we will call it infodiversity and use the current host `infodiversity.cse.usf.edu`.

@glciampaglia will rename the repository once it is safe to do so.
