### ISSUE TITLE
Evaluating 3bjij3

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#24]
Brendan shared with us an interesting project called 3bij3, which seems to provide an environment for testing news recommender systems. Robert will read the paper and Saumya will try to run the software and see what it looks like.

Code: https://github.com/FeLoe/3bij3 
Paper: https://computationalcommunication.org/ccr/article/view/11/11

**Comment by RobertAndion** [comment]
I have finished reading the paper and have a few key takeaways we can discuss:

1. Diverse information on many topics is better than diverse information on a few
2. An algorithm has to balance between overwhelming a user with information and filtering too much and creating an information bubble (Perhaps we should rank good news highest but also mix in non-news tweets to not overwhelm the user)
3.Numbers alone are not enough. They suggest that you need to know the deeper effects of your algorithm, how is it affecting users access to all information? Is it polarizing them? Is it restricting their ideas/beliefs?
4. Even when using the algorithm they take 33% of results as random and from different sets of articles (theirs has access to news RSS streams not twitter) See number 2.
5. All options are displayed on one screen to prevent any "scroll bias"
6. In our case the users have already chosen what they want to see, I think a bit of randomness (2,4) would help this.
7. Their platform with hundreds of users saw little to no lag when running on 64GB ram and 16 threads. I anticipate we will need less as they have the database, stream and app all running on one machine. We will have a machine for the Database, Twitter is our "stream" and this plus the app will be running on another system.

**Comment by glciampaglia** [comment]
We discussed these findings. We already agreed with team Dartmouth and team USF that we want to add some "random" tweets, so it is good to know that other people recommend it too. Also good to know that EC2 machines do not need to be super strong, based on the fact their app was much heavier than ours.
