### ISSUE TITLE
Fix Pug container issue

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#29]
It seems there is one or possibly multiple Pug containers that need to be styled properly. We would like this to happen to two different types of containers:
1) Body container (@saumyabhadani95): text should wrap correctly; right now it is overflowing outside of the container. 
2) Image container (@RobertAndion) images should have the correct aspect ratio; right now the image retains the height from the data, but the width from the container, resulting in a lot of distorted, overstretched containers.

Fixing this issue should also fix issue #4.

**Comment by RobertAndion** [comment]
Both #1 and #2 are completed. #1 we figured out an attribute to add to the text to allow to form with the container. We still need to fix scaling on window size changes but that is not included in this issue (applies to text and images)  For the images we were able to use Javascript to force a ratio we chose that looked good on both mobile and pc devices.
