### ISSUE TITLE
Create a new association table between User and Tweet

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#30]
This is needed in the case we go for the [1-auth flow](https://docs.google.com/presentation/d/1EVVINhwjBZ4dHKs1WBh2EVtKendLJ9avMybCihK7Bgk/edit), where VolunteerScience pre-loads the tweets in our database. 

After landing on the page (3), we create a session (5a) using the data pre-loaded into the database by VS. When creating the session, we also add an entry for each tweet into the `tweet_in_session` table, so that we keep track of the engagements.

**Comment by RobertAndion** [comment]
The new table has been created and added.
