### ISSUE TITLE
When using 2-auth, load tweets in new association table

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#31]
Because we do not know yet if we are going to go with [1-auth or 2-auth flow](https://docs.google.com/presentation/d/1EVVINhwjBZ4dHKs1WBh2EVtKendLJ9avMybCihK7Bgk/edit), we will use the association table between user and session (see #30) to load the tweets. In the case of 2-auth flow, when the user loads Truman (5b) if there are already tweets in that table, then the app should display those tweets. Otherwise, it will call the home_timeline endpoint, fetch the results, load them in the new association table, and then display those tweets. (This way, if the user reloads the tab, the same tweets will be displayed.)

We will need this implemented anyway, regardless of whether we go with 1-auth, because we want to run beta testing with our own authentication (it would impractical to wait for VS).

**Comment by RobertAndion** [comment]
#30 Has since been completed. Now we need to add the logic in code to use the table which will be a bit more complex and done after our milestone for the 29th (3/29/21) is done.

**Comment by glciampaglia** [comment]
We decided, for testing purposes, we want hold off on implementing this feature, just because in that way we can have people load more tweets in their tests. Therefore we will implement this *after* the big beta testing with our lab members. We updated the milestone accordingly.

**Comment by saumyabhadani95** [comment]
Robert will begin implementing the logic for this.

**Comment by glciampaglia** [comment]
This has been implemented. 

We met with YG and we will handle the authorization ourselves, without VS. This means that we will follow a "new" [2-auth workflow](https://docs.google.com/presentation/d/1EVVINhwjBZ4dHKs1WBh2EVtKendLJ9avMybCihK7Bgk/edit#slide=id.p), where the first authentication in the screening survey will be done by us. If then the user agrees to take part in the Rockwell part of the experiment, then the user is already authenticated and we fetch the tweets. The logic here stays the same because if the user reloads the page, then the tweets are already in the DB and we don't need to call the home_timeline endpoint again. (Unless of course the cookie has expired.)
