### ISSUE TITLE
Fix SSLError when loading cards from home timeline

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#34]
On some platforms the callback fails due to exceptions like the following:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='spcampus.usf.edu', port=443): Max retries exceeded with url: /home/2021/01/07/usf-adopts-call-me-mister-program-to-boost-the-number-of-male-teachers-of-color/?utm_campaign=Admissions&utm_source=twitter&utm_medium=social&utm_term=Article&utm_content=Call%20Me%20MISTER (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

Right now @RobertAndion has added a try/catch block but we need to understand what is causing the error, since the tweet loads fine on the Twitter web client (https://twitter.com/USouthFlorida/status/1375432987354001412)

**Comment by glciampaglia** [comment]
We need to address this problem systematically. Right now we only make sure that the exception is caught. We should try to recover from the issue. For example, we could attempt the request again (perhaps 1 or 2 times), and only if these retries fail, we silently ignore. More broadly, this may be connected to #35, since our instance needs to fire up a lot of requests to load all cards.

**Comment by RobertAndion** [comment]
This is completed. If you get the chance to test on your end @glciampaglia  (As you were most susceptible) please let me know.
