### ISSUE TITLE
Open all links in new tabs 

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#38]
When a user clicks on a like, the link should open in a new tab or window. The `target` attribute in the link should be set to `_blank`: 

https://www.w3schools.com/tags/att_a_target.asp

**Comment by RobertAndion** [comment]
This is now fixed. @saumyabhadani95 Line 64 of script.pug needs to be fixed. we no longer have an actor so the link is broken. We need the direct link of the user to be pipelined to that location.
