### ISSUE TITLE
Link metadata not properly extracted

### ISSUE THREAD

**Issue by filmenczer** [glciampaglia/infodiversity-mock-social-media#40]
In some cases there are problems displaying content associated with a link, like title and description. Maybe the issue is redirection? Here are a couple examples where you seem to be getting a 404 or 400. In these examples, the link seems to work for me.
<img width="578" alt="Screen Shot 2021-04-01 at 4 33 45 PM" src="https://user-images.githubusercontent.com/10651090/113353114-32bb6f80-930b-11eb-8a87-a84f66dab6a6.png">
<img width="566" alt="Screen Shot 2021-04-01 at 4 36 44 PM" src="https://user-images.githubusercontent.com/10651090/113353124-36e78d00-930b-11eb-8eba-c2e5edafc789.png">

**Comment by RobertAndion** [comment]
For the articles we are depending on the website using the proper tags for twitter. However there is some variance in the way some websites do this. I will further optimize this and should be a very easy fix. Thank you for pointing this out as before it was a theoretical fix and now it seems mandatory.

**Comment by filmenczer** [comment]
If you do not find the Twitter card metadata, look for the OG (open Graph) metadata. It is used by Facebook but also by Twitter if Twitter card tags are missing. https://developers.facebook.com/docs/sharing/webmasters/

**Comment by saumyabhadani95** [comment]
We are using BeautifulSoup to parse the HTML pages so this issue should be fixed. We are looking for OG metadata.

**Comment by glciampaglia** [comment]
This is fixed. Closing.
