### ISSUE TITLE
Display name is on separate lines on mobile

### ISSUE THREAD

**Issue by aychen5** [glciampaglia/infodiversity-mock-social-media#43]
This is low priority, but the display name is on a new line when I test the app on mobile. There's probably only so much you can do to accommodate all mobile types/screen widths, but thought I'd flag in case it's an easy fix.

![Screenshot_20210402-125812_Chrome](https://user-images.githubusercontent.com/34891965/113437607-e7f63200-93b4-11eb-82d3-9e3315f654fe.jpg)
![Screenshot_20210402-125653_Chrome](https://user-images.githubusercontent.com/34891965/113437618-ee84a980-93b4-11eb-91ff-f0d5f3cea8c6.jpg)

**Comment by RobertAndion** [comment]
We are planning on making the platform more dynamic with text sizes and hopefully that will help this issue. Furthermore either removing the X minutes ago (or moving it) could help or the idea of always loading the handle under the username could allow this to be more flexible to smaller screens.

**Comment by glciampaglia** [comment]
This should be solvable in two ways: the @name should go on a new line. This should overflowing on the  "xx minutes ago" part. If either the @name or the screen name are too long for the device width, they can be clipped using CSS. See this video here: https://www.youtube.com/watch?v=X6tTBxEmZCE

**Comment by saumyabhadani95** [comment]
This is done. However if the @name or screen name is too long then there is a chance that the profile image would be squished. But hopefully the names should not be that long.
