### ISSUE TITLE
Getting rid of url for attached images

### ISSUE THREAD

**Issue by aychen5** [glciampaglia/infodiversity-mock-social-media#44]
Would it be possible remove the visible urls for tweets that have attached images? 

![Capture d’écran 2021-04-02 à 12 29 58 PM](https://user-images.githubusercontent.com/34891965/113438149-fc86fa00-93b5-11eb-90d8-50bf0202bd8b.png)

Here's one where there's an image (underlined and circled in red) and a clickable link (in blue)

<img width="416" alt="Capture d’écran 2021-04-02 à 12 40 22 PM" src="https://user-images.githubusercontent.com/34891965/113438533-bed6a100-93b6-11eb-8835-ed80320642d0.png">

**Comment by RobertAndion** [comment]
This is something more in @saumyabhadani95 's domain. I believe we may be able to detect when there is an image with the same link and thus remove the text link. I think by default we are pasting all links into the text as this is what we were doing prior to having images inserted. Thank you for noticing this, it will be discussed when Saumya and I next meet.

**Comment by saumyabhadani95** [comment]
Removed the visible URLs.

**Comment by glciampaglia** [comment]
The previous fix removed the blue link but the black one. It seems there are tweets with a t.co link to the tweet itself! We need to see the raw JSON of those payloads.

**Comment by glciampaglia** [comment]
We took a look, and we decided that we will not remove black links, because if we did so, some tweets (like the one below) would become hard to understand. It seems that in this case the link is an integral part of the text.

![image](https://user-images.githubusercontent.com/1506860/115301020-abedfb80-a12e-11eb-82df-a2312bfea74b.png)
