### ISSUE TITLE
When authorizing redirect to landing page immediately

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#45]
Currently, the callback for the Twitter auth loads the tweets. If there is any problem there, the user remains on the Twitter redirecting page 

![image](https://user-images.githubusercontent.com/1506860/113617612-8936ef80-9624-11eb-8248-6049d4f78137.png)

Instead, Twitter should redirect directly to a landing page, which then should perform the loading. If there is any error, the page should display the traceback.

**Comment by saumyabhadani95** [comment]
Added a landing with page with placeholder.
