### ISSUE TITLE
Complete the database

### ISSUE THREAD

**Issue by saumyabhadani95** [glciampaglia/infodiversity-mock-social-media#48]
Following tables are still left to be loaded for the beta testing release:

* [x] truman_user
* [x] click
* [x] tweet_in_session (tweet_seen, tweet_retweeted and tweet_favorited)

**Comment by RobertAndion** [comment]
Retweet .js should be where a javascript pool is created to connect to the database. This needs some consideration but here if we make one pool we can handle the views, tweet_in_session metrics and click all in one file. We could also forward traffic from retweet.js to the python pool but we would need a serious queue system to prevent data loss this way

**Comment by saumyabhadani95** [comment]
I have included the insertion to tweet_in_session (for views and engagements) and click in one file. The Database system right now may be crude and we need to see how it performs in beta testing. However, a queue system to prevent data loss would most probably be needed to be safe. We can create another issue for the queue system. Closing this issue.
