### ISSUE TITLE
Clean up source code from passwords and other security hazards

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#49]
Some source files like [here](https://github.com/glciampaglia/infodiversity-mock-social-media/blob/main/twitter_api/database_access/database_access.py) or [here](https://github.com/glciampaglia/infodiversity-mock-social-media/blob/main/twitter_api/database_access/database_access_legacy.py) include login information in the open. This can pose a security risk. We need to make sure all instances like this are cleaned up, and we need to change the login information on the affected hosts.

In particular, this needs to happen:

- [x] Reinstate the old config file used for the database
- [x] Change username/password for all the accounts on AWS that were exposed in source code
- [x] Run a massive find on all source code to see if there any other source files with passwords hard-coded in them

**Comment by saumyabhadani95** [comment]
Done.
