### ISSUE TITLE
Create container for beta testing

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#5]
We need to create a docker image of the full app. We will deploy the container on AWS for beta testing.

**Comment by RobertAndion** [comment]
This can be done fairly soon, a docker file that pulls from git hub and builds what we need shouldnt be too hard to set up.

**Comment by RobertAndion** [comment]
Created a working docker image. I need Saumya to sum up exactly what packages we need for node and it will be completely built (as a prototype still, it wont run automatically)
