### ISSUE TITLE
If both embedded image and card are available only render embedded image

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#51]
When a tweet contains both an embedded image and a card, only show the embedded image. Sample below:

![image](https://user-images.githubusercontent.com/1506860/116924599-18d0bd80-ac26-11eb-9ce8-40eb5024d13d.png)

**Comment by RobertAndion** [comment]
This looks weird as they were the same but sometimes they are unrelated. Do we just want to remove all of them? For Quotes we are making this assumption already.

**Comment by glciampaglia** [comment]
Yes!

**Comment by RobertAndion** [comment]
@saumyabhadani95 I can do this one if you want. We just have to set a new boolean hasEmbed or something similar and if it does set the card image = "" and it will not display on the platform. Did we still want the title and description of the card? If we remove it entirely we will lose the article link as well. This aspect of it would take more logic than stated above.

**Comment by glciampaglia** [comment]
The duplicate image is not being displayed anymore, however we are still working on the link, and need to switch to `expanded_url`.

**Comment by saumyabhadani95** [comment]
I tried a few things to render the links and make them clickable but it's proving to be difficult in Pug. But it's can be done I think. Almost there.

**Comment by saumyabhadani95** [comment]
All the inks are clickable now and `expanded_url` is displayed instead of `url`
