### ISSUE TITLE
No action feedback on retweet / like buttons

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#53]
When the user clicks on the retweet / like button, the following should happen:
- [x] The counter should increment by one (if number is < 1000, will need to read back from a string the number in Pug) 
- [x] The button should change color
- [x] The button becomes disabled. 
 
The last point is to signal to the user that they cannot undo the retweet or like. We may need to specify this in the FAQ / user instructions, since people will likely expect Rockwell to behave like the Twitter client.

**Comment by saumyabhadani95** [comment]
This is done.
