### ISSUE TITLE
Update "upload" icon

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#55]
Current icon is red and looks more like an "exit" icon. Let's use something more neutral and that is associated to uploading, like one of these: ~~https://thenounproject.com/term/upload/~~ https://icons.getbootstrap.com/

Also let's add a text label, something like "Upload data".

This button is likely to change or disappear when we have the actual experiment, but for now we can use this implementation for testing the database.

**Comment by saumyabhadani95** [comment]
This is done.
