### ISSUE TITLE
URL Image doesn't show.

### ISSUE THREAD

**Issue by parushgera** [glciampaglia/infodiversity-mock-social-media#58]
The tweet doesn't show the image associated with the URL, but the image is visible on Twitter after re-twitting it from the platform.
<img width="433" alt="after_retwitting" src="https://user-images.githubusercontent.com/44270091/117207963-94677180-adc2-11eb-9219-5462511d2985.PNG">
<img width="483" alt="before_retwiting" src="https://user-images.githubusercontent.com/44270091/117207964-95000800-adc2-11eb-85d4-12c0221d46ce.PNG">

**Comment by RobertAndion** [comment]
This is a case of a website using a tag different that what we are looking for, CardInfo.py can be adjusted to search for the tag that website is using upon inspection of the html. This is a big help thank you

**Comment by glciampaglia** [comment]
It seems the og tag is provided, so we need to investigate why it didn't load. The URL of that particular tweet is: https://www.hindustantimes.com/cities/mumbai-news/vaccination-for-those-above-45-yrs-of-age-resumes-in-mumbai-today-101620197123734.html

**Comment by saumyabhadani95** [comment]
It should be fixed.
