### ISSUE TITLE
Reverse proxy settings

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#59]
The reverse proxy has been configured to map `/app` to the node.js app, which runs on port 3000. To make sure this works, we need to update the flask callback to redirect to that instead of the raw ip address.

**Comment by saumyabhadani95** [comment]
I tried this before the beta testing on Wednesday but the feed was not rendering correctly. There were some weird changes like the profile pictures were not displaying and there was some random string in place of the date. On the console there was the following error : "this script is not allowed to redirect."

**Comment by glciampaglia** [comment]
Minh has updated the reverse proxy rules. They are the following:

```
infodiversity.cse.usf.edu -> 18.222.180.62:5000
infodiversity.cse.usf.edu/app/ -> 18.222.180.62:3000
infodiversity.cse.usf.edu/callback  -> 18.222.180.62:5000/callback
infodiversity.cse.usf.edu/<ANYTHING> -> 18.222.180.62:3000/<ANYTHING> (default rule)
```

**Comment by glciampaglia** [comment]
We need to a new rule:
```
infodiversity.cse.usf.edu/engagements -> 18.222.180.62:5050
```

**Comment by glciampaglia** [comment]
This has been fixed.
