### ISSUE TITLE
Integrate twitter authorizer into Qualtrics for screening survey

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#6]
This is needed as part of the screening survey. Not sure if this is part of the truman app or whether creating a standalone app would be better.

**Comment by glciampaglia** [comment]
We discussed the issue. Based on our recollection of discussion with the rest of the team, it was decided we will have this at the end of the survey. The user will click on the "Sign in with Twitter" button (see [here](https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter)), and we will fetch all the information needed for determining eligibility. The user will be then redirected to a landing page that simply says: Thank you, we will be in touch.

**Comment by glciampaglia** [comment]
We reviewed how to do this in Qualtrics. There is an embedded data option [that allows to access URL parameters](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/embedded-data/#SettingValuesFromTheSurveyURL) included in the survey link. Then, at the end of the survey, we need to create a custom end-of-survey message with a link that has the same parameters. This link will point to Truman. We need to figure out how to implement this second step in Qualtrics.

**Comment by saumyabhadani95** [comment]
I was able to create a custom end-of-survey message with a link that has the parameters from the survey URL. I have published a Qualtrics to test the same. You can view the survey [here](https://usf.az1.qualtrics.com/jfe/form/SV_1GNBVHU0REsyhjU?workerId=ABCD1435&hitId=35hgfsbdu&assignmentId=vbwjebwufg)
