### ISSUE TITLE
Data losses due to too many connections

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#61]
During the testing May 5th testing session we noticed that for many people the app was not recording all data. This affected both engagements, impressions, and even timeline tweets. We discovered that each client was creating too many connections to the database. To load the timeline, each single tweet would require its own connection. This quickly filled up the connection pool, and once the maximum connections are being used, any additional new connection was being silently discarded. To solve this problem, we decided to optimize the usage of connections.

What has been done:
- When receiving the payloads from the Twitter API (home timeline), instead of sending the ID/rank/tweet in session info/etc. of each single tweet separately, we now store all this information into a single JSON payload.
- We increased to 250 the value of `max_connections` in the [RDS config file].(https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections).

What needs to be done:
- [x] Use a single payload also when inserting data into the `user_tweet` table
- [x] Need to test whether 250 for RDS `max_connections` is enough
- [x] In the backend, modify asyncio call to keep trying until successful (or max attempts is reached). Currently we simply discard after the 1st attempt.
- [x] Optimize the storage of engagements. Use a single connection for saving all the engagements (retweets, likes, tweets seen and clicks). 

Related tasks (not part of this issue):
- Make sure that any failed attempt is logged properly (see #62), right now the connections were failing silently.
- And add the capability to store the engagements at regular time intervals (see #69).

**Comment by saumyabhadani95** [comment]
Logging is still not done. 

And the last requirement is half done. I don't know yet how to store engagements at regular intervals.

**Comment by glciampaglia** [comment]
We moved the last two bullet points to their own issues. The rest has been completed, so closing for now.
