### ISSUE TITLE
Keep logs of the backend

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#62]
We need to make sure that both the python and node.js parts of the backend keep track of a log where to store all information, including warnings, debugging messages (if running in debug mode), and errors. 

Ideally, it would be great to have both node.js and python log to the same file, but since this is probably, complicated, we will keep two separate log files. With python, we can use [the built-in logging module](https://docs.python.org/3/library/logging.html), and save to a file. With node.js, we'll simply keep a file open and save messages there.

We need to:
- [x] Set up logging module in python
- [x] Set up logging file in node.js
- [x] Go through code add INFO messages for any relevant step as part of its normal flow
- [x] Go through code and make sure any exception is logged at the ERROR level (or above)

**Comment by RobertAndion** [comment]
We can use a similar system to this for the node logging: https://github.com/RobertAndion/DiscordMusicBotNode/blob/main/index.js

**Comment by saumyabhadani95** [comment]
I tried to add logging to the python code base but once I added it to the twitter authenticator server, it just didn't start. I waited for like five minutes, but still it didn't start. The code must be going into an infinite loop somewhere or maybe logging and flask just don't together, I don't know. I will look into it.

**Comment by saumyabhadani95** [comment]
Logging is added to python codebase as well.
