### ISSUE TITLE
Alter tweet table

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#63]
In the tweet table we want to store the full JSON payload we get from the Twitter API. This will prevent us from losing data after the experiment is performed, in case the tweets get deleted. However, if a tweet is deleted, we need to make sure we do not display it to the user. So we need also an additional flag to keep track of deleted tweets.

In summary, we need to:

- [x] Add `tweet_json` column in DB to store tweet JSON in the tweet table
- [x] Add `is_deleted` column with boolean flag to mark if a tweet has been deleted or not (default: False)

**Comment by saumyabhadani95** [comment]
Added the columns.
