### ISSUE TITLE
Remove session and merge with tweet_in_session table

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#65]
Once we have implemented #64, we can simplify the database, remove the `session` table, and merge it with `tweet_in_session` one. The table will simply associate a Twitter user_id with the IDs of the tweets (tweet_id) of their timeline.  

Also, instead of having multiple boolean columns for tweet_seen / tweet_retweeted / tweet_favorited, we can have a single string column that records the type of engagement. This can be one of three possible strings, `seen`, `retweeted`, and `favorited`, along with the timestamp. (There can be multiple rows, since the user can see, retweet, and favorite a tweet.) We should probably discuss this a bit more before deciding this last step.

**Comment by glciampaglia** [comment]
We have implemented the part about the multiple boolean columns. The new table is up, so we only need to remove the `session` table.

**Comment by saumyabhadani95** [comment]
Removed `session` table.
