### ISSUE TITLE
Disable counter after engagement

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#68]
If you click retweet or like multiple times the counter will keep incrementing. It should be locked instead. See this video here:

https://user-images.githubusercontent.com/1506860/118048750-b9239200-b34a-11eb-9ded-7dcaa9efd3f4.mp4

In addition, it would be nice if we could show the button already red when the user already engaged with the tweet before loading rockwell. But I don't know if this information is available through the home timeline.

**Comment by saumyabhadani95** [comment]
This is Done.
