### ISSUE TITLE
Save engagements/impressions data in browser LocalStorage at regular time intervals (polling)

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#69]
Right now, for testing purposes, we have a red button that users need to press to make sure that the all the activity data (engagements, impressions, etc.) are stored into the database. In the experiment, this could lead to data losses if the participants forget to press the red button, so instead we should have the client poll the server at regular intervals and send any new data.

**Comment by saumyabhadani95** [comment]
We can call a Javascript function at regular intervals with the following code:

const interval = setInterval(send_data, 1000);

This code will call the function send_data every 1 minute (1000 ms). 

However, if the user closes / refreshes / clicks "back" before clicking the upload button then there may be some loss of data (especially if the interval is high like 10 mins). In that case, we can use [onbeforeunload](https://stackoverflow.com/questions/17975068/calling-js-functions-on-browser-tab-close) which is used to give a promt whenever a user leaves a web page.

**Comment by glciampaglia** [comment]
We discussed this issue. Since participants need to go back to YG as proof of completion, we need to still display a button for exiting the experiment. So, it's not so important anymore that we upload the data at regular intervals. We can assume that all participants will click on the button (otherwise they don't get paid), and simply send the data then. That said, it's also a good idea to make sure that the data are [stored locally in the browser](https://developer.chrome.com/docs/devtools/storage/localstorage/?utm_source=devtools) so that refreshing the page doesn't lose any data. So we will not need to upload the data at regular intervals anymore. However, it's still a good idea to update the data in local storage at regular intervals, using setInterval.

**Comment by saumyabhadani95** [comment]
Data is now being stored locally in the browser.
