### ISSUE TITLE
Design Issue : Populating the feed very slow

### ISSUE THREAD

**Issue by saumyabhadani95** [glciampaglia/infodiversity-mock-social-media#8]
Populating the feed is very slow right now and the page just keeps loading for some seconds. We need to speed up the process and also develop a placeholder UI like a progress bar or a nice "Loading" sign so that it's user friendly.

**Comment by RobertAndion** [comment]
This has been sped up greatly but still has a similar issue. I believe we will be able to further speed up this process and perhaps load tweets in smaller batches than 20. Perhaps 10 with a load more button at the bottom as discussed. The only issue would be making sure at least the next 10 are unique. After that hopefully new tweets would have appeared on their feed. The tracking function may or may not have to be adjusted for this technique depending on whether we repopulate the page or append. I believe we had decided that re population would be the preferred method.

**Comment by glciampaglia** [comment]
We discussed this issue. When we have the landing page with spinning wheel / progress bar (see issue #2) this issue will be taken care of. Closing for now.
