### ISSUE TITLE
Update text in authorization screen

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#81]
In the authorization screen, we need to update the following paragraph:

> If you are willing, we ask that you please click the button below so that we can obtain your Twitter username. This ensures that we get an authentic username. The button will briefly redirect you to Twitter and ask you to allow the Volunteer Science application to fetch your username only. (If you are on a mobile device, you might receive a pop-up warning.) Volunteer Science is an academic research platform developed by researchers at Northeastern University.

with this (see text in bold):

> If you are willing, we ask that you please click the button below so that we can obtain your Twitter username. This ensures that we get an authentic username. The button will briefly redirect you to Twitter and ask you to allow the **InfoDiversity** application to fetch your username only. (If you are on a mobile device, you might receive a pop-up warning.) **InfoDiversity** is an academic research platform developed by researchers at **University of South Florida, Dartmouth College, and Indiana University**.

**Comment by RobertAndion** [comment]
This has been changed.
