### ISSUE TITLE
Add a tmux startup script 

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#83]

**Comment by RobertAndion** [comment]
The script to start the 5 applications through tmux has been completed. The file can be found at the root directory as start.sh and can be ran by running sh start.sh

**Comment by glciampaglia** [comment]
The script should take one argument, the command. There are three possible commands:
1. start
2. restart
3. stop

**Comment by RobertAndion** [comment]
The script is complete and can be run with bash start.bash <arg> where the arg can be 0, 1 or 2. 
0: Start
1: Stop
2: Restart

**Comment by glciampaglia** [comment]
We can use getopts to parse the command line: https://en.wikipedia.org/wiki/Getopts

**Comment by glciampaglia** [comment]
We think that for now this is good enough for development. For real deployments we are going to use something [Gunicorn](https://gunicorn.org/). Closing for now.
