### ISSUE TITLE
Remove configuration file from version control

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#87]
To make sure that we can run the app on multiple locations (laptop, AWS, etc.), we want to remove the `config.ini` from version control and add it to the `.gitignore` file. Instead, we will create a blank copy of the configuration file, called `config.ini.sample` and commit that to github. 

When somebody needs to deploy a new version on the server, they can simply push the new code to github, ssh into the server, and from there pull the new code. Since the `config.ini` is not under version control, that will not overwrite the configuration file.

**Comment by glciampaglia** [comment]
It looks like some of the changes in #85 were accidentally rolled back. Before we complete this, we need to make sure all those changes have been re-instated.

**Comment by RobertAndion** [comment]
The original issue and added comment are both complete.
