### ISSUE TITLE
Image card and description are not retrieved for @cseUSF

### ISSUE THREAD

**Issue by saumyabhadani95** [glciampaglia/infodiversity-mock-social-media#9]
Don't know if this is important but I just discovered that the card images, description and summary is not retrieved for @cseUSF account. @cseUSF is not that important but don't want it happening for important accounts.

Observed:

![Screenshot from 2020-12-15 10-31-23](https://user-images.githubusercontent.com/14941766/102236073-0cd79f80-3ec1-11eb-8ace-8c9a4f86e4a7.png)

Needed:

![Screenshot from 2020-12-15 10-32-03](https://user-images.githubusercontent.com/14941766/102236144-22e56000-3ec1-11eb-8008-5b297c2b8e6c.png)

**Comment by RobertAndion** [comment]
If you could send me the link to this tweet or check the html for the og:: tags... If they are not present my script will not find the image, description or title. However you would still have the link you can embed. The system right now only deals with websites that are made for tweet cards. Perhaps this one is missing it or has another tag format. If you give the links I can try and find out. However checking for more tags may slow down this process further.

**Comment by RobertAndion** [comment]
This is due to the websites not having the proper tags. If the professor has other tags we can look for we can try for those too but for now there is no solution for this.

**Comment by glciampaglia** [comment]
We discussed issue and we decided that we will decide whether to fix this issue or not after testing on AWS with several users. If the issue is common (meaning that many websites do not use OG tags), then we will think if there is a way to fix it. Reopening for now.

**Comment by RobertAndion** [comment]
<meta property="og:title" content="USF to confer more than 5,000 degrees virtually on Dec. 12">
   <meta property="og:description" content="The fall class includes a graduate making university history, a husband and wife graduating together and a 19 year old only one year removed from high school.">
   <meta property="og:url" content="https://www.usf.edu/news/2020/usf-to-confer-more-than-5000-degrees-virtually-on-dec-12.aspx">
   
   The USF site uses this syntax. I will change the code to try to find the specific og::twitter tags first and if it cannot find those it will look for these and if that fails return nothing as it currently does.

**Comment by RobertAndion** [comment]
<meta property="og:title" content="USF to confer more than 5,000 degrees virtually on Dec. 12">
   //<meta property="og:description" content="The fall class includes a graduate making university history, a husband and wife //graduating together and a 19 year old only one year removed from high school.">
//   <meta property="og:url" content="https://www.usf.edu/news/2020/usf-to-confer-more-than-5000-degrees-virtually-on-//dec-12.aspx">

**Comment by RobertAndion** [comment]
` <meta property="og:title" content="USF to confer more than 5,000 degrees virtually on Dec. 12">
   <meta property="og:description" content="The fall class includes a graduate making university history, a husband and wife graduating together and a 19 year old only one year removed from high school.">
   <meta property="og:url" content="https://www.usf.edu/news/2020/usf-to-confer-more-than-5000-degrees-virtually-on-dec-12.aspx">`

**Comment by RobertAndion** [comment]
I have given the new code to Saumya to be pushed. Yet to be tested

**Comment by glciampaglia** [comment]
We improved the code a bit, so now we should be covering all cases, but we will keep the issue open until we have a way to beta test it with users (same as with #10).

**Comment by glciampaglia** [comment]
Could any of these libraries help for this issue?
- https://github.com/michaelhelmick/lassie/
- https://github.com/coleifer/micawber/
- https://github.com/scrapinghub/extruct

**Comment by RobertAndion** [comment]
This has been fixed to near perfection. Only websites with strange tags will not be found. If we have beta testers save images that don't load like they should we can see what tags they are using and add them.
