### ISSUE TITLE
Remove empty space at end of feed

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#90]
In the main pug file there are a lot of `<br/>` elements at the end of the feed, this creates an empty space and makes it harder for users to know that they need to reach the end of the screen (even though they reached the end of the feed). We need to remove them and leave only enough to make sure that the end of the feed coincides with the bottom of the screen.

**Comment by RobertAndion** [comment]
This has been fixed but as a side effect the scrolling bounds for activating the next page error must be corrected. (Button never activates now)

**Comment by glciampaglia** [comment]
It looks like the listener function `viewCountScrollBased` has been deleted from `public/js/retweet.js` in 6896cb74414a2c5f70a60d400071c6ea04809b32

The file seems to have been heavily changed, so we don't know if we should restore the function only, and where.

**Comment by glciampaglia** [comment]
We have created a new issue for the merge problem; closing this now.
